---
title: "Symfony Secrets Kullanımı"
weight: 40
---

:imagesdir: /images/en/user

== 1. Giriş

Symfony paketleri ve yapılandırması kullanmanın büyük avantajlarından biri, Symfony'nin sağladığı özelliklerin tüm potansiyelinden yararlanabilmektir.
Bu özelliklerden biri **secrets** (gizli değerler) özelliğidir (daha fazla bilgi için aşağıdaki bağlantıya bakın).

- link:https://symfony.com/doc/current/configuration/secrets.html[Symfony Secrets]

Symfony secrets, hassas değerleri şifrelenmiş bir "kasa" içinde güvenli biçimde saklamamıza olanak verir. Ayrıca bu değerler ortama (environment) göre de tanımlanabilir.

SAML yapılandırmamızda, kolay erişilmesini istemediğimiz sertifikalar ve özel anahtarlar gibi değerleri saklamak için secrets kullanılabilir.

Secrets eklemek için önce link:https://symfony.com/doc/current/configuration/secrets.html[Symfony belgelerindeki kurulum adımlarını] takip ederek gerekli adımları atın.

== 2. Yeni bir secret ekleme

Gerekli kurulum tamamlandıktan sonra, yeni bir secret eklemek için aşağıdaki komutu çalıştırabilirsiniz.

`php bin/console secrets:set <NAME_OF_ENV_VARIABLE>` (konsol sizden değeri girmeyi isteyecektir)

- örn: `php bin/console secrets:set SAML_SP_PRIVATE_KEY`


== 2. Yapılandırmada secret kullanma

Secret'lar, diğer env özellikleri gibi `'%env(...)'` kullanılarak yapılandırmaya eklenebilir.

Aşağıdaki örnek, saml yapılandırmasından alınmış kısmi bir snippet'tir:

[source,yaml]
----
hslavich_onelogin_saml:

  # ...

  sp:

     ...

    # SuiteCRM için (sp) özel anahtar
    privateKey: '%env(SAML_SP_PRIVATE_KEY)%'

    # ...
----

== 3. Symfony önbelleğini temizleyin

⚠️ `.env.local` dosyanızda değişiklik yaptıktan sonra lütfen kök dizinden `./bin/console cache:clear` çalıştırdığınızdan veya Yönetici Menüsünden `Repair and Rebuild` işlemini gerçekleştirdiğinizden emin olun.
